# CHAPTER 4 Numpy Basics: Arrays and Vectorized Computation

In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2 = my_arr*2

CPU times: user 13.9 ms, sys: 5.18 ms, total: 19.1 ms
Wall time: 18.6 ms


In [5]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

CPU times: user 713 ms, sys: 178 ms, total: 891 ms
Wall time: 893 ms


## 4.1 The Numpy ndarray: A Multidimensional Array Object

In [6]:
data = np.random.randn(2,3)

In [7]:
data

array([[-0.31032478, -0.37881244,  0.43461411],
       [ 1.19378455,  1.1618047 , -0.34794909]])

In [8]:
data * 10

array([[-3.10324776, -3.78812441,  4.34614111],
       [11.93784545, 11.61804699, -3.47949092]])

In [10]:
data + data

array([[-0.62064955, -0.75762488,  0.86922822],
       [ 2.38756909,  2.3236094 , -0.69589818]])

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

In [13]:
data1 = [6,1.5,8,0,1]

In [14]:
arr1 = np.array(data1)

In [15]:
arr1

array([6. , 1.5, 8. , 0. , 1. ])

In [16]:
data2 = [[1,2,3,4],[1,2,3,4]]

In [17]:
arr2 = np.array(data2)

In [18]:
arr2

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [19]:
arr2.ndim

2

In [20]:
arr2.shape

(2, 4)

In [21]:
arr1.dtype

dtype('float64')

In [22]:
arr2.dtype

dtype('int64')

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros(3,6)

TypeError: data type not understood

In [25]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
np.empty((2,3,2))

array([[[-0.00000000e+000, -1.49457796e-154],
        [ 2.96439388e-323,  0.00000000e+000],
        [-2.03770574e-263,  1.58817677e-052]],

       [[ 4.22278667e-090,  1.88692633e+185],
        [ 1.26105324e-076,  6.57702775e-038],
        [ 3.99910963e+252,  8.34402697e-309]]])

In [29]:
%timeit t1 = np.array(np.arange(10000))

8.44 µs ± 148 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [30]:
%timeit t2 = np.asarray(np.arange(10000))

5.71 µs ± 73 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [31]:
%timeit t3 = np.arange(10000)

5.18 µs ± 108 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [32]:
arr1 = np.array([1,1,1],dtype = np.float64)

In [33]:
arr2 = np.array([1,1,1],dtype = np.int32)

In [34]:
arr1.dtype

dtype('float64')

In [35]:
arr2.dtype

dtype('int32')

In [37]:
arr2.dtype.a

4

In [38]:
arr = np.array([1,2,3,4])

In [40]:
float_arr = arr.astype(np.float64)

In [42]:
float_arr.dtype

dtype('float64')

In [43]:
float_arr[0]=0

In [44]:
arr

array([1, 2, 3, 4])

In [45]:
float_arr

array([0., 2., 3., 4.])

In [46]:
arr = np.array([1.1,0.5,1.6])

In [47]:
arr.astype(np.int32)

array([1, 0, 1], dtype=int32)

In [48]:
arr

array([1.1, 0.5, 1.6])

In [50]:
np.floor(arr) == arr.astype(np.int32)

array([ True,  True,  True])

In [55]:
numeric_string = np.array(['1.2','2.4'],dtype = np.string_)

In [56]:
numeric_string

array([b'1.2', b'2.4'], dtype='|S3')

In [57]:
numeric_string.astype(np.float32)

array([1.2, 2.4], dtype=float32)

In [58]:
a = np.array([1.4,-1.5,666])

In [59]:
a.dtype

dtype('float64')

In [60]:
a.astype(np.uint16)

array([    1, 65535,   666], dtype=uint16)

In [61]:
a.astype(arr.dtype)

array([  1.4,  -1.5, 666. ])

In [67]:
empty_uint32 = np.empty(8,'f4')

In [68]:
empty_uint32

array([0.   , 1.875, 0.   , 2.   , 0.   , 2.125, 0.   , 2.25 ],
      dtype=float32)

In [69]:
arr = np.array([[1.,2,3],[4,5,6]])

In [70]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [71]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [72]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [76]:
1/np.zeros_like(arr)

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf],
       [inf, inf, inf]])

In [78]:
arr **0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [81]:
arr2 = np.array([[1,2.,4]])

In [82]:
arr2>arr

array([[False, False,  True],
       [False, False, False]])

In [83]:
arr = np.arange(10)

In [84]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
arr[5]

5

In [86]:
arr[5:8]

array([5, 6, 7])

In [87]:
arr[5:8]=12

In [88]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [89]:
arr_slice = arr[5:8]

In [90]:
arr_slice[1]=123

In [91]:
arr

array([  0,   1,   2,   3,   4,  12, 123,  12,   8,   9])

In [92]:
arr_slice[:]=1

In [93]:
arr

array([0, 1, 2, 3, 4, 1, 1, 1, 8, 9])

In [94]:
arr3d = np.arange(12).reshape(2,2,3)

In [95]:
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [96]:
arr3d[0]

array([[0, 1, 2],
       [3, 4, 5]])

In [97]:
arr3d[0]=99

In [98]:
arr3d

array([[[99, 99, 99],
        [99, 99, 99]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [99]:
arr2d = np.arange(1,7).reshape(2,3)

In [100]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [108]:
arr2d[0:1]

array([[1, 2, 3]])

In [128]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']).T

In [129]:
data = np.random.randn(7,4)

In [130]:
data

array([[-1.34801381, -1.16146982, -0.832572  , -1.65734061],
       [-1.68490915, -1.4492285 , -1.24405473,  1.03606941],
       [-0.54034844, -0.51967581,  2.23819427,  0.0301734 ],
       [ 0.33741316,  0.87332654,  1.34471148, -0.10102156],
       [-1.17434838,  0.23013308,  1.45051537, -0.24550508],
       [-0.42221942, -0.61047062,  0.62093803, -1.52169865],
       [-0.01585276,  1.43968952, -0.16923056, -0.50438981]])

In [139]:
cond  = (names == 'Bob') | (names == 'Will')

In [140]:
data[~cond]

array([[-1.68490915, -1.4492285 , -1.24405473,  1.03606941],
       [-0.42221942, -0.61047062,  0.62093803, -1.52169865],
       [-0.01585276,  1.43968952, -0.16923056, -0.50438981]])

In [141]:
data[data<0]=0

In [142]:
data

array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.03606941],
       [0.        , 0.        , 2.23819427, 0.0301734 ],
       [0.33741316, 0.87332654, 1.34471148, 0.        ],
       [0.        , 0.23013308, 1.45051537, 0.        ],
       [0.        , 0.        , 0.62093803, 0.        ],
       [0.        , 1.43968952, 0.        , 0.        ]])

In [143]:
arr = np.empty((8,4))

In [144]:
for i in range(8):
    arr[i]=i

In [145]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [159]:
arr[list(range(8))]

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [160]:
arr = np.arange(32).reshape((8, 4))

In [161]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [162]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [163]:
ard = np.array([[1, 5, 7, 2], [0, 3, 1, 2]])

In [164]:
ard

array([[1, 5, 7, 2],
       [0, 3, 1, 2]])

In [165]:
arr[ard]

array([[[ 4,  5,  6,  7],
        [20, 21, 22, 23],
        [28, 29, 30, 31],
        [ 8,  9, 10, 11]],

       [[ 0,  1,  2,  3],
        [12, 13, 14, 15],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [166]:
zrr[ard.T]

NameError: name 'zrr' is not defined